name: Build And Release APK

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease || true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            **/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/release/*.apk

      - name: Generate Tag
        id: tag
        run: echo "tag=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Android Build ${{ steps.tag.outputs.tag }}
          files: |
            **/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/release/*.apk
